// Content bundled with the ryux-rules CLI. Original ryux.design work (MIT licensed): written from
// scratch based on public standards & research (Nielsen's 10 heuristics 1994, NNGroup UX research,
// WCAG 2.2, Apple HIG, Material). Full source: docs/design-rules.md.

// All RX rules. Four design layers: RX-C filter, RX-H heuristics, RX-N NNGroup guidelines, RX-L
// local. Plus RX-K: a clean-code add-on (the ryux-code concern), outside the core design gate.
export const RULES: Record<string, string> = {
  "RX-C-01": "Every design decision references at least one real screen_id as evidence.",
  "RX-C-02": "Avoid generic template layouts without a contextual reason.",
  "RX-C-03": "No numbers or statistics without a real source; empty is better than made up.",
  "RX-C-04": "No invented testimonials, names, or photos of people.",
  "RX-C-05": "Mark placeholders clearly ([REAL DATA], [LOGO]); never disguise them as final.",
  "RX-C-06": "Copy is specific about the action and the benefit; avoid empty clichés and generic CTAs.",
  "RX-C-07": "Limited color palette: 2 to 3 core colors plus 1 accent.",
  "RX-C-08": "Consistent spacing and type scale (e.g. multiples of 4 or 8).",
  "RX-C-09": "Designer notes are written by a human, not generated by AI.",
  "RX-H-01": "Visibility of system status: a process over 1 second shows status plus an estimate.",
  "RX-H-02": "Match the real world: language and ordering follow user habits.",
  "RX-H-03": "Control and freedom: provide cancel, undo, and a clear way out.",
  "RX-H-04": "Consistency and standards: follow platform conventions and internal patterns.",
  "RX-H-05": "Error prevention: confirm destructive actions, validate before sending.",
  "RX-H-06": "Recognition over recall: show options and context, reduce memory load.",
  "RX-H-07": "Flexible and efficient: offer shortcuts for expert users.",
  "RX-H-08": "Aesthetic and minimalist: every element has a reason, lead with the relevant info.",
  "RX-H-09": "Error recovery: clear message, state the cause, give a concrete way out.",
  "RX-H-10": "Short contextual help at the point of use.",
  "RX-H-11": "WCAG AA contrast: normal text >= 4.5:1, large text >= 3:1.",
  "RX-H-12": "Body text >= 12px; touch targets >= 44x44px.",
  "RX-H-13": "Keyboard focus is visible; focus order is logical.",
  "RX-H-14": "Complete states (loading/empty/error/success); no overflow; respect safe areas.",
  "RX-N-01": "Feedback matches response-time limits: over 1s show loading, over 10s show progress plus an estimate.",
  "RX-N-02": "Single-column forms, labels above the field (not only inside it).",
  "RX-N-03": "Validate inline and keep the user's input on error.",
  "RX-N-04": "Minimize fields; mark required/optional clearly; use sensible defaults.",
  "RX-N-05": "Error messages state the problem plus the fix, near the source; don't blame the user.",
  "RX-N-06": "Total cost (shipping, admin, tax) is transparent before the user commits.",
  "RX-N-07": "A reviewable order summary plus a progress indicator for multi-step flows.",
  "RX-N-08": "Low sign-in friction: support guest checkout or fast login.",
  "RX-N-09": "Honest trust: no fake urgency or scarcity; real security signals.",
  "RX-N-10": "Correct mobile input: keyboard matches the type (numeric for amounts/OTP), autofill.",
  "RX-N-11": "Prevent mistakes: confirm irreversible actions (delete, pay) plus undo when possible.",
  "RX-N-12": "Wayfinding: a clear 'where am I' title, a back/cancel button always available.",
  "RX-L-01": "QRIS: the amount and merchant name are clear before confirmation.",
  "RX-L-02": "Virtual account: copy-number button, payment deadline, per-bank guidance.",
  "RX-L-03": "OTP: offer a channel (SMS or WhatsApp); a reasonable resend countdown.",
  "RX-L-04": "Fees (admin, shipping, tax) are visible before the user commits.",
  "RX-L-05": "Address: support a landmark and house details, not just a map pin.",
  "RX-L-06": "Money uses the local Rupiah format (Rp + thousands separators).",
  "RX-L-07": "Copy is natural Bahasa Indonesia, not a stiff translation from English.",
  "RX-L-08": "References and patterns come from real Indonesian apps.",
  "RX-L-09": "Paylater or installments: show the limit, tenor, and total cost clearly.",
  "RX-L-10": "e-KYC: framing guidance and the reason for collecting data before the camera opens.",
  "RX-K-01": "Comments explain the reason (why), not restate what the code already makes obvious.",
  "RX-K-02": "Variable and function names are specific and meaningful; avoid data, temp, helper, manager without context.",
  "RX-K-03": "Remove dead code, unused imports, and commented-out blocks; don't leave empty TODOs.",
  "RX-K-04": "Follow the style of the surrounding file (format, naming, patterns); don't impose a new one.",
  "RX-K-05": "Avoid over-engineering: no abstractions or config for needs that don't exist yet.",
  "RX-K-06": "Handle errors with actionable messages; don't swallow errors silently.",
};

// Core rules, always installed (evidence + honest content).
export const CORE_RULES = ["RX-C-01", "RX-C-03", "RX-C-04", "RX-C-05", "RX-C-09"];

export interface Concern {
  id: string;
  label: string;
  hint: string;
  rules: string[];
}

// Concerns (like antislop: ui / copywriting / etc.) mapped to RX rules.
export const CONCERNS: Concern[] = [
  {
    id: "ui",
    label: "UI and visual",
    hint: "generic patterns, palette, spacing, consistency, states",
    rules: ["RX-C-02", "RX-C-07", "RX-C-08", "RX-H-04", "RX-H-08", "RX-H-14", "RX-N-12"],
  },
  {
    id: "copy",
    label: "Indonesian copywriting",
    hint: "natural language, Rupiah, error messages, CTAs",
    rules: ["RX-C-06", "RX-L-06", "RX-L-07", "RX-H-09", "RX-N-05"],
  },
  {
    id: "a11y",
    label: "Accessibility",
    hint: "contrast, text size, touch targets, focus, states",
    rules: ["RX-H-11", "RX-H-12", "RX-H-13", "RX-H-14"],
  },
  {
    id: "ux",
    label: "Applied UX patterns (NNGroup)",
    hint: "forms, errors, checkout, trust, response time",
    rules: ["RX-N-01", "RX-N-02", "RX-N-03", "RX-N-05", "RX-N-06", "RX-N-07", "RX-N-09", "RX-N-11"],
  },
  {
    id: "local",
    label: "Indonesian patterns",
    hint: "QRIS, VA, OTP, fees, address, paylater, e-KYC",
    rules: ["RX-L-01", "RX-L-02", "RX-L-03", "RX-L-04", "RX-L-05", "RX-L-09", "RX-L-10"],
  },
  {
    id: "code",
    label: "Clean code",
    hint: "honest comments, meaningful names, no dead code, consistent style",
    rules: ["RX-K-01", "RX-K-02", "RX-K-03", "RX-K-04", "RX-K-05", "RX-K-06"],
  },
];

export const ALL_CONCERN_IDS = CONCERNS.map((c) => c.id);
export const RULES_VERSION = "0.2.0";
export const MCP_NAME = "ryux";
export const MCP_URL = "https://mcp.ryux.design/mcp";
export const MCP_ADD_CMD = `claude mcp add --transport http ${MCP_NAME} ${MCP_URL}`;
export const MARK_START = "<!-- ryux-rules:start -->";
export const MARK_END = "<!-- ryux-rules:end -->";
